- src/app/api/ai-plugin/route.ts
- src/app/api/tools/coinflip/route.ts
- src/app/config.ts
This PR implements the `bitte-ai/agent-sdk` and adds a compatible plugin manifest.
- Initialized and configured `agent-sdk`
- Created and structured plugin manifest
- Add a test route called `coinflip` 
Fixes #1
> Fixes #1: Implement agent-sdk and plugin manifest

- package.json
- pnpm-lock.yaml
- src/app/api/ai-plugin/route.ts
- src/app/api/tools/get-user/route.ts
This PR updates the plugin manifest `/api/ai-plugin` to include the following tools:
- `get-user`
Fixes #3
> Fixes #3: Add tool to get NEAR wallet context

- CONTRIBUTING.md
Created a CONTRIBUTING.md file with:
- Project setup steps using pnpm
- Branch naming conventions (feat/, fix/, docs/, chore/)
- Pull request process and formatting rules
- Code standards and best practices
Fixes #8
> Fixes #8 : Created Contribution guidelines

- src/app/api/ai-plugin/route.ts
- src/app/api/tools/create-btc-mpc-txn/route.ts
This PR updates the plugin manifest (/api/ai-plugin) to include a new tool: 
- create-btc-mpc-txn
This tool enables the creation of a Bitcoin transaction using multi-party computation (MPC) signing.
Fixes #5
> Fixes #5 : Add tool to create BTC MPC transaction

- code_of_conduct.md
- issue_template.md
- pull_request_template.md
Set up basic community and contribution guidelines:
- `CODE_OF_CONDUCT.md` using Contributor Covenant
- `.github/PULL_REQUEST_TEMPLATE.md`
- `.github/ISSUE_TEMPLATE/bug_report.md` and `feature_request.md`
Helps standardize contributions and maintain project health.
FIxes #12
> Created Code of Conduct, PR Template, and Issue Template 

- next.config.ts
- package.json
- pnpm-lock.yaml
Fixes deployment issues related to next.config
> Fixes next config for deployment

- src/app/page.tsx
Fixes layout issues in the Roadmap section for mobile devices by adjusting spacing, alignment, and responsiveness to ensure proper display across screen sizes.
Fixes #22
> Fix #22 Roadmap Section Responsiveness on Mobile

- src/app/api/ai-plugin/route.ts
- src/app/api/tools/get-btc-balance/route.ts
- src/app/api/tools/get-user/route.ts
- src/app/api/tools/send-btc-txn/route.ts
This completes the testing of MPC transaction using Near chain signatures and agents SDK
> Test BTC mainnet txn and code cleanup

- src/app/page.tsx
This PR adds the agent link to the launch button.
> Update agent link 

- package.json
- pnpm-lock.yaml
- src/app/api/ai-plugin/route.ts
- src/app/api/tools/create-btc-mpc-txn/route.ts
- src/app/api/tools/get-btc-balance/route.ts
- src/app/api/tools/get-user/route.ts
- src/app/api/tools/send-btc-txn/route.ts
- src/app/config.ts
This pull request implements searchParams of all values used in api instead of using values from the headers.
> Fix : change mb-metadata header to searchParams

- src/app/api/ai-plugin/route.ts
- src/app/api/tools/get-btc-balance/route.ts
- src/app/api/tools/get-user/route.ts
This PR changes variable name as per ai plugin requirements
> Fix variable namings

- src/app/layout.tsx
- src/app/page.tsx
This PR addresses the issue where metadata (title, description, OG tags) was not rendering correctly across pages. The update ensures that metadata is dynamically set based on the current route/page content.
List the changes made in this pull request, including the relevant context and reasoning.
Fixes #33
> Fixes #33 Metadata not rendering properly

- src/app/api/tools/create-btc-mpc-txn/route.ts
- src/app/api/tools/get-btc-balance/route.ts
- src/app/api/tools/get-user/route.ts
- src/app/api/tools/send-btc-txn/route.ts
This pull request attempts to add support to consume the inputs by agent using mb-metadata header
> Test : mb-metadata headers with agent inputs

- src/app/api/ai-plugin/route.ts
Add hardcoded `PLUGIN_URL` string
> Fix : PLUGIN_URL string

- src/app/dashboard/page.tsx
Added `/dashboard` page to Bitcoin Agent deployment.
Fixes #43
> Fixes #43 : Create dashboard page 

- package.json
- pnpm-lock.yaml
- src/app/dashboard/page.tsx
- src/app/page.tsx
- src/components/ui/tabs.tsx
Create the generic UI for the `/dashboard` route.
Fixes #47
> Fixes #47 : Create Dashboard UI

- src/app/dashboard/page.tsx
This pull request adds features such as user's bitcoin wallet address and balance load in dashboard.
Fixes #45
> Fix #45 : complete data loading and state management of dashboard page

- src/app/dashboard/page.tsx
- src/components/dashboard/TransactionHistory.tsx
- src/lib/parseBitcoinTransactions.ts
Fetches and displays real-time transaction data from the blockstream API in the All, Send, and Received tables.
Fixes #56
> Fix#56 : Load Transaction Data in dashboard on frontend

- src/app/dashboard/page.tsx
Replaced the existing QR code icon with a more intuitive QrCode icon from lucide-react to improve UI clarity.
Fixes #67
> Fixes #67 : Update QR Code Icon for BTC Address

- src/app/api/tools/create-btc-mpc-txn/route.ts
- src/app/api/tools/get-btc-balance/route.ts
- src/app/api/tools/get-btc-txns/route.ts
- src/app/api/tools/get-user/route.ts
- src/app/api/tools/send-btc-txn/route.ts
- src/app/dashboard/page.tsx
- src/components/dashboard/TransactionHistory.tsx
This PR performs general code cleanup across the codebase to improve readability, maintainability, and consistency. This includes removing unused code, improving naming conventions, and applying consistent formatting.
Fixes #75
> Fixes #75 : Code Cleanup: General Refactoring and Improvements

- pull_request_template.md
This PR fixes the pull request template to ensure clarity, consistency, and proper usage across contributors.
Fixes #80
> Fixes #80 : pull request template

- src/app/dashboard/page.tsx
Update content in description page to reflect correct agent info and its status.
Fixes #83
> Fixes #83 : add content changes

- README.md
This PR update the documenttation in the `Readme.md` with the latest changes.
Fixes #88
> Fixes #88 : Update Readme content with latest changes

- issue_template.md
This PR updates the issue template.
Fixes #89
> Fixes #89 : Fix the Issue template

- package.json
- pnpm-lock.yaml
Add a `bitte.ai/chat` and react packages.
Fixes #93
> Fixes #93 : Add bitte.ai/chat & react packages 

- src/app/api/widget/chat/route.ts
- src/app/api/widget/history/route.ts
Creates proxy routes to handle chat and history form bitte agent widget
Fixes #94
> Fixes #94 : Create proxy routes

- src/app/chat/layout.tsx
Uses Bitte Wallet Context Provider in /chat
Fixes #102
> Fixes #102 : Bitte Wallet context

- src/app/api/ai-plugin/route.ts
- src/app/api/tools/create-btc-mpc-txn/route.ts
- src/app/api/tools/get-btc-balance/route.ts
- src/app/api/tools/get-btc-txns/route.ts
- src/app/api/tools/get-user/route.ts
- src/app/api/tools/send-btc-txn/route.ts
Added below fixes and enhancements to get agent ready for verification.
Fixes #106
> Fix #106 : Fixes for agent verification

- src/app/page.tsx
This PR revise the project timeline displayed on the landing page to reflect the current project progress accurately.
Fixes #112
> Fixes#112 : Aligned Project Timeline on Landing Page

- src/app/api/ai-plugin/route.ts
This PR adds past agent tools for MPC signing after review based on new timeline and NEAR intents integration.
> chore: add past agent tools after review

- README.md
Updates the README to include features explaining NEAR intents for swapping and buying Bitcoin, and add the roadmap section with updated links.
Fixes #125
> Fixes #125: Update README with NEAR intents features & roadmap links

- docs/expanded-competitive-analysis.md
- docs/technical-roadmap.md
This PR add an expanded competitive analysis document in Markdown format under `/docs` to highlight Bitcoin Agent’s differentiation against bridges, messaging protocols, Bitcoin L2s, and AI agents.
Fixes #156
> Fixes #156: Added expanded competitive analysis to docs

- package.json
- pnpm-lock.yaml
- src/app/api/chat/route.ts
- src/app/api/history/route.ts
- src/app/dashboard/page.tsx
- src/components/ChatWidget.tsx
This PR integrate the Bitte Widget component into the project dashboard to allow direct interaction with the Bitcoin Agent through the Bitte interface.
Fixes #160
> Fixes #160: Add Bitte Widget Component to Dashboard 

- src/app/dashboard/page.tsx
- src/app/widget-iframe/page.tsx
This PR update styling/placement of Bitte Widget so it integrates cleanly without breaking existing UI elements.
Fixes #162
> Fixes #162: Fix Bitte Widget UI Interference on Dashboard

- src/app/widget-iframe/layout.tsx
- src/app/widget-iframe/page.tsx
This PR updates the widget integration so the agent can properly read and use the connected wallet context.
Fixes #166
> Fixes #166 : Fix wallet context issue in widget

- src/app/dashboard/layout.tsx
- src/app/dashboard/page.tsx
- src/app/widget-iframe/page.tsx
This PR update the components to remove hydration issues and ensure consistent rendering.
Fixes #170
> Fixes #170: Fix Next.js hydration issues in dashboard and widget

- docs/initial-review-and-user-feedback.md
This PR adds a new markdown file `/docs/initial-review-and-user-feedback.md` summarizing early usage insights, challenges, strengths, and next steps based on internal testing, external builders feedback.
Fixes #174
> Fixes #174 : Add Initial Review & User Feedback Document

- docs/value-flow-diagram.md
This PR adds a new markdown file `/docs/value-flow-diagram.md` containing detailed flow diagrams for Bitcoin Agent.  
Fixes #176
> Fixes #176 : Add Value Flow Diagram Document 

- README.md
This PR adds Bitcoin Agent to the public agent registry and include the public agent link in the project documentation for easy discovery and integration.
Fixes #184
> Fixes #184: Register Bitcoin Agent and Update Documentation 

- docs/progress-summary.md
This PR update the existing `progress-summary.md` document to include **Month 2 progress**.  
Fixes #186
> Fixes #186 : Update Progress Summary with Month 2 Progress 

- src/app/page.tsx
This PR update the project landing page to include a v2.0 tag highlighting the latest release milestone.
Fixes #188
> Fixes #188 : Add v2.0 Tag

- src/app/page.tsx
This PR updates the roadmap timeline according to current progress.
Fixes #190
> Fixes #190: Update Roadmap Timeline on Landing Page

- src/app/next/page.tsx
This PR adds custom styling and adding subtle animations to improve visual appeal and user engagement.
Fixes #208
> Fixes #208: Add Custom Styling to /next Page
